version: "3"

services:
  web:
    image: webdevops/php-apache:7.4-alpine
    ports:
      - "4500:80"
    volumes:
      - ./www:/app
      - ./php.ini:/opt/docker/etc/php/php.ini

  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root